### ISSUE TITLE
Download Jar file

### ISSUE THREAD

**Issue by ebertti** [Wovenware/killbill-braintree#5]
Hi, 

Where a can download de jar file?

I can't find on maven

**Comment by wwerodriguez** [comment]
Hello @ebertti, we received your question and will promptly respond this for you.

**Comment by wwerodriguez** [comment]
Hi @ebertti.
Just to clarify, you are looking for the Braintree Kill Bill Plugin, or are you looking for the Braintree SDK?
Thanks for your patience and response. It will allow me to help you better.

**Comment by ebertti** [comment]
Hi, I looking dor Braintree Kill Bill Plugin

**Comment by wwerodriguez** [comment]
Hi @ebertti.
We only provide the plugin as source code to be compiled to a jar, and then installed in Kill Bill. It is not available on Maven. You will find that all plugins provided by Kill Bill are offered this way.

I hope this helps.

**Comment by joseph-jaojoco** [comment]
Hi, I already turn the source code to jar file. I was sucessfully download it to killbill but the plugin itself is not registered to killbill. Any solution on this? thanks.
![image](https://user-images.githubusercontent.com/93753505/152334769-e355356d-26d0-481e-a2fd-edcb287a579d.png)
![image](https://user-images.githubusercontent.com/93753505/152335060-6bfbb6e2-a5b6-470e-a6d7-00023b041097.png)

**Comment by wwjfrodriguez** [comment]
Hello @joseph-jaojoco,
Please validate if the location of your file is correct and verify if your KillBill version is: 0.22.z and try again the installation using the following command:

```
kpm install_java_plugin braintree-plugin --from-source-file=./braintree-plugin-0.1.0-SNAPSHOT.jar --destination=/var/lib/killbill/bundles
```

**Comment by joseph-jaojoco** [comment]
hi @wwerodriguez ,
killbill: 0.22.27
kaui:2.0.9
As per checking the plugin is installed in correct dir.
![image](https://user-images.githubusercontent.com/93753505/152461576-118c561c-4f76-4de1-8a88-55d26385af4e.png)

Is it okay if the plugin dont have groupid artifactid and packaging?
![image](https://user-images.githubusercontent.com/93753505/152461919-abff9563-c6bf-4d87-8b95-2eb211505ac7.png)

as per checking in logs.,
when I'm installed the stripe plugin in kaui it registering the plugin while the manually installed braintree didn't.

samed issue ref: https://groups.google.com/g/killbilling-users/c/QRLYdzjbo0E/m/cXRrAFDGAQAJ

thanks

**Comment by joseph-jaojoco** [comment]
image for reference:
<img width="1301" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/93753505/152467403-192e898f-f615-4438-bfc4-6252b44778ed.png">
<img width="1261" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/93753505/152467411-44dfba46-d48c-4743-a26e-e239bcf1f1f4.png">

**Comment by wwjfrodriguez** [comment]
@joseph-jaojoco 
 It is possible that the payment method was not created correctly.
 
 When you create a payment method using KAUI at least the following properties must be included for the plugin to work correctly:

- bt_nonce: Payment method nonce received from Braintree.
- bt_customer_id: The customer ID assigned to the customer in Braintree's vault. Only required if not already present as an account Custom Field, if provided it will be set as Custom Field.
- payment_method_type: The type of payment method that is being created. Possible values include CARD, PAYPAL or ACH. 
These values are case insensitive. Not to be confused with Braintree's payment instrument type, which includes subdivisions of these three general types.

![image](https://user-images.githubusercontent.com/36242659/152592780-c0ca961e-83f6-46bf-a56f-6a9d283d3e6b.png)

**Comment by joseph-jaojoco** [comment]
hello @wwerodriguez ,
still the same.
![image](https://user-images.githubusercontent.com/93753505/152638035-2945a8b3-f6ce-449f-a48d-3232e33301c9.png)
I found out that the OSGI servlet didn't registered the manually installed plugin. Any idea on this?

**Comment by wwjfrodriguez** [comment]
@joseph-jaojoco 
Can you share the content of your logs file (killbill.out) ?

**Comment by joseph-jaojoco** [comment]
Hi @wwerodriguez  here is my sample logs. 
keyword titles: Attempt in adding payment method logs, braintree, stripe
Please see attached file.
Thank you
/Users/josephjaojoco/Documents/entropy-projects/gridloc_aaa/logs.txt

**Comment by joseph-jaojoco** [comment]
Hi @wwerodriguez here is my sample logs.
keyword titles: Attempt in adding payment method logs, braintree, stripe
Please see attached file.
Thank you

/Users/josephjaojoco/Documents/entropy-projects/gridloc_aaa/logs.log

**Comment by joseph-jaojoco** [comment]
Hi @wwerodriguez here is my sample logs.
Please see attached file.
[logs.log](https://github.com/Wovenware/killbill-braintree/files/8031194/logs.log)
keyword titles: stripe, braintree, adding payment method logs

Thank you

**Comment by wwjfrodriguez** [comment]
Thanks @joseph-jaojoco!
Can you also provide me the response of this request?
`/1.0/kb/pluginsInfo`

![image](https://user-images.githubusercontent.com/36242659/153233300-fcd110d0-63d4-4f50-ac53-a2635a38aa91.png)

**Comment by joseph-jaojoco** [comment]
Hi @wwerodriguez,
Sure, Here's the response
![image](https://user-images.githubusercontent.com/93753505/153238191-05bcf868-e014-4afe-b32d-b50ec8175e16.png)

**Comment by joseph-jaojoco** [comment]
hello @wwerodriguez ,
Any idea on this issue?

**Comment by wwjfrodriguez** [comment]
@joseph-jaojoco 
I have had to investigate and I suspect that there is something wrong with your KillBill Core installation or configuration. Can you provide me with all the details of how you installed and configured KillBill core?

**Comment by joseph-jaojoco** [comment]
hi @wwerodriguez ,
here's my configuration,
I run it in docker
![image](https://user-images.githubusercontent.com/93753505/156282990-58b37787-0f53-41e8-9054-05e289515d4f.png)

**Comment by wwjfrodriguez** [comment]
Hi @joseph-jaojoco thanks for sharing!
I ran your `docker-compose` file in a Vagrant  virtual machine with Ubuntu and did not can to reproduce your error. Did you change something in the plugin code before you compile it?

These are the steps that I did to install the plugin in my VM:
```
# Compiling the plugin
mvn clean package -DskipTests

# Copying the jar to the killbill container
docker cp braintree-plugin-0.1.0-SNAPSHOT.jar aaa_killbill:/tmp/braintree-plugin-0.1.0-SNAPSHOT.jar

# kpm install java plugin
docker exec -it aaa_killbill bash
kpm install_java_plugin braintree-plugin --from-source-file=/tmp/braintree-plugin-0.1.0-SNAPSHOT.jar --destination=/var/lib/killbill/bundles
exit

# Restarting killbill container
docker restart aaa_killbill
```

**Comment by joseph-jaojoco** [comment]
Hi @wwjfrodriguez ,I've been doing it wrong. I've build the source code with vscode export jar not in mvn.
Thanks a lot. it's working now. 
![image](https://user-images.githubusercontent.com/93753505/156685355-269a8373-5560-42bd-a9f5-fb844abdf762.png)

**Comment by wwjfrodriguez** [comment]
@joseph-jaojoco  
Glad to help!
