### ISSUE TITLE
Cannot install plugin: missing version

### ISSUE THREAD

**Issue by shaunie2fly** [Wovenware/killbill-braintree#7]
HI Guys, I hope you can help me.

I downloaded the killbill-braintree source and compiled it to a jar.

I'm now attempting to install the plugin with KPM using your example in the readme but I get this error.

**_kpm install_java_plugin braintree-plugin --from-source-file ./killbill-braintree.jar --destination /var/lib/killbill/bundles_**
```

Cannot install plugin: missing version
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/gems/kpm-0.10.3/lib/kpm/base_installer.rb:175:in `install_plugin_from_fs'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/gems/kpm-0.10.3/lib/kpm/tasks.rb:193:in `install_java_plugin'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/gems/kpm-0.10.3/bin/kpm:8:in `<top (required)>'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/bin/kpm:26:in `load'
/opt/kpm-0.10.3-linux-x86_64/lib/vendor/ruby/2.2.0/bin/kpm:26:in `<main>'
```

Do you know what I am doing incorrectly?
Thanks
Shaun

**Comment by wwjfrodriguez** [comment]
Hello @shaunie2fly, we received your question and will promptly respond to this for you.

**Comment by wwjfrodriguez** [comment]
@shaunie2fly please validate if the location of your file is correct and verify if your KillBill version is: `0.22.z` and try again the installation using the following command:
```
kpm install_java_plugin braintree-plugin --from-source-file=./braintree-plugin-0.1.0-SNAPSHOT.jar --destination=/var/lib/killbill/bundles
```

**Comment by shaunie2fly** [comment]
Hi , Thanks.  Issue resolved.  Looks like you have to have the jar filename formatted as in the example which includes version details.

`kpm install_java_plugin braintree-plugin --from-source-file=./braintree-plugin-0.1.0-SNAPSHOT.jar --destination=/var/lib/killbill/bundles`

Have a lovely weekend ;)
